export const dataList = [
  {
    id: 1,
    Dessert: "Frozen Yougurt",
    Calories: 159,
    Fat: 6.0,
    Carbs: 24,
    Proteins: 4.0,
    Sodium: 87,
    Calcium: 14,
    Iron: 1,
  },
  {
    id: 2,
    Dessert: "Ice Cream",
    Calories: 237,
    Fat: 9.0,
    Carbs: 37,
    Proteins: 4.3,
    Sodium: 129,
    Calcium: 8,
    Iron: 1,
  },
  {
    id: 3,
    Dessert: "Eclair",
    Calories: 262,
    Fat: 16.0,
    Carbs: 24,
    Proteins: 6.0,
    Sodium: 337,
    Calcium: 6,
    Iron: 7,
  },
  {
    id: 4,
    Dessert: "CupCake",
    Calories: 305,
    Fat: 3.7,
    Carbs: 67,
    Proteins: 413,
    Sodium: 129,
    Calcium: 3,
    Iron: 8,
  },
  {
    id: 5,
    Dessert: "ginger Bread",
    Calories: 356,
    Fat: 16.0,
    Carbs: 49,
    Proteins: 3.9,
    Sodium: 327,
    Calcium: 7,
    Iron: 16,
  },
];
export const resultList = [
  {
    cmpSubject: "FIRST LANGUAGE",
    fmWritten: 90,
    fmOral: 10,
    fmTotal: 100,
    moWritten: 63,
    moOral: 10,
    moTotal: 73,
    moGrade: "A",
  },
  {
    cmpSubject: "SECOUND LANGUAGE",
    fmWritten: 90,
    fmOral: 10,
    fmTotal: 100,
    moWritten: 53,
    moOral: 9,
    moTotal: 62,
    moGrade: "A",
  },
  {
    cmpSubject: "MATHEMATICS",
    fmWritten: 90,
    fmOral: 10,
    fmTotal: 100,
    moWritten: 76,
    moOral: 9,
    moTotal: 85,
    moGrade: "A+",
  },
  {
    cmpSubject: "PHYSICAL SCIENCE",
    fmWritten: 90,
    fmOral: 10,
    fmTotal: 100,
    moWritten: 89,
    moOral: 7,
    moTotal: 96,
    moGrade: "AA",
  },
  {
    cmpSubject: "LIFE SCINCE",
    fmWritten: 90,
    fmOral: 10,
    fmTotal: 100,
    moWritten: 85,
    moOral: 5,
    moTotal: 90,
    moGrade: "AA",
  },
  {
    cmpSubject: "HISTORY",
    fmWritten: 90,
    fmOral: 10,
    fmTotal: 100,
    moWritten: 63,
    moOral: 9,
    moTotal: 72,
    moGrade: "A",
  },
  {
    cmpSubject: "GEOGRAPHY",
    fmWritten: 90,
    fmOral: 10,
    fmTotal: 100,
    moWritten: 75,
    moOral: 10,
    moTotal: 85,
    moGrade: "A+",
  },
  {
    cmpSubject: "OPTIONAL SUBJECT",
    fmWritten: "",
    fmOral: "",
    fmTotal: "",
    moWritten: "",
    moOral: "",
    moTotal: "",
    moGrade: "",
  },
];

const dummyData = [
  {
    userName: "Super Admin",
    email: "superadmin@greenprice.hk",
    userAccess: "Admin",
    accountStatus: true,
  },
];
